### ISSUE TITLE
Default + customizable themes

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#51] opened 2018-07-29 00:43 UTC
Allowing users to select from premade themes and make their own custom themes if they really don't like our given themes.

**Comment by PeterGhimself** [comment] 2018-07-29 00:44
Would be cool to have this done directly through the UI, and have a configuration file that it reads from to get the configurable style values/writes to when updating the theme.

**Comment by MartensCedric** [comment] 2019-12-30 03:26
duplicate of #153

**Closed by MartensCedric** 2019-12-30 03:26 UTC
Labels: Basestation, Enhancement, GUI, Good first issue
