### ISSUE TITLE
Fix wheel motor numbering

### ISSUE THREAD

**Issue by MartensCedric** [space-concordia-robotics/robotics-prototype#173] opened 2019-09-12 22:16 UTC
In `robot/rover/MobilePlatform/commands.h`, remove the need for the todo seen here : https://github.com/space-concordia-robotics/robotics-prototype/commit/46a28fa0168fcf09380338e88b9e3291eba176f2

- [ ]  make sure motor numbering makes sense in both closed and open loop (1 to 6 not 0 to 5)
- [ ] make sure motor order is correct (1 to 6 actually turns motors 1 to 6)

**Comment by PeterGhimself** [comment] 2019-09-27 19:22
This may be of some use, @vashmata drew this up during ERC after we did continuity checks and checked in the code to make sure the right values were assigned. Would not be a bad idea to re-test again anyway.

![rotated-wheels](https://user-images.githubusercontent.com/19865282/65796368-67f56900-e13a-11e9-8e12-619bca8ccd76.jpg)

**Comment by vashmata** [comment] 2020-01-11 03:57
For some context, I believe that the manner in which the microcontroller code was written has it such that in one mode the motors are linked to the values 0 to 5 instead of 1 to 6.

In the arm code, motors are always associated with values 1 to 6. The reason is that when a variable which is supposed to hold a motor number has been initialized but a motor number has never been assigned to it, the variable will contain 0. Because of this, situations where values are not assigned to the variable will result in an error rather than unexpected behaviour.

**Comment by vashmata** [comment] 2020-03-07 03:36
bump

**Comment by vashmata** [comment] 2020-03-07 08:19
To complement @PeterGhimself 's picture, here's a picture from Jeff's elec documentation... I have a feeling that the PDS motor numbering is different from the wheel teensy numbering
![image](https://user-images.githubusercontent.com/32688392/76139860-7e291e80-6022-11ea-9b31-760716be82ff.png)
![image](https://user-images.githubusercontent.com/32688392/76139861-7ff2e200-6022-11ea-9de9-c91fdcf4f89d.png)

**Comment by fauziame** [comment] 2020-03-07 21:37
> To complement @PeterGhimself 's picture, here's a picture from Jeff's elec documentation... I have a feeling that the PDS motor numbering is different from the wheel teensy numbering
> ![image](https://user-images.githubusercontent.com/32688392/76139860-7e291e80-6022-11ea-9b31-760716be82ff.png)
> 
> You can find it here under "Loads" https://docs.google.com/document/d/1TRe7r--ptHSgJJRi9-591QSPD0hNo5rdP2sQKe8Wdfk/edit#

This is the numbering model used in commands.h

M1 = RF
M2 = RM
M3 = RB
M4 = LF
M5 = LM
M6 = LB

**Comment by AFknUsername** [comment] 2020-03-14 18:03
What Fauzi did is what I had before i changed it back for testing lol.
All good though, I had to test it anyways so good thing that it happened earlier

**Closed** 2020-06-08 01:06 UTC
Labels: Bug
